package com.github.ocraft.s2client.bot.enums;

import com.github.ocraft.s2client.protocol.data.UnitType;

import java.util.HashMap;
import java.util.Map;

public enum UnitTypeNames {
    TERRAN_ARMORY("Armory"),
    TERRAN_AUTO_TURRET("Auto Turret"),
    TERRAN_BANSHEE("Banshee"),
    TERRAN_BARRACKS("Barracks"),
    TERRAN_BARRACKS_FLYING("Flying Barracks"),
    TERRAN_BARRACKS_REACTOR("Barracks Reactor"),
    TERRAN_BARRACKS_TECHLAB("Barracks Tech Lab"),
    TERRAN_BATTLECRUISER("Battlecruiser"),

    TERRAN_CYCLONE("Cyclone"),
    TERRAN_BUNKER("Bunker"),
    TERRAN_COMMAND_CENTER("Command Center"),
    TERRAN_COMMAND_CENTER_FLYING("Flying Command Center"),
    TERRAN_ENGINEERING_BAY("Engineering Bay"),
    TERRAN_FACTORY("Factory"),
    TERRAN_FACTORY_FLYING("Flying Factory"),
    TERRAN_FACTORY_REACTOR("Factory Reactor"),
    TERRAN_FACTORY_TECHLAB("Factory Tech Lab"),
    TERRAN_FIREBAT("Firebat"),
    TERRAN_FUSION_CORE("Fusion Core"),
    TERRAN_GHOST("Ghost"),
    TERRAN_GHOST_ACADEMY("Ghost Academy"),
    TERRAN_HELLION("Hellion"),
    TERRAN_HELLION_TANK("Hellion Tank"),
    TERRAN_LIBERATOR("Liberator"),
    TERRAN_LIBERATOR_AG("Liberator"),
    TERRAN_MARAUDER("Marauder"),
    TERRAN_MARINE("Marine"),
    TERRAN_MEDIC("Medic"),
    TERRAN_MEDIVAC("Medivac"),
    TERRAN_MISSILE_TURRET("Missile Turret"),
    TERRAN_MULE("MULE"),
    TERRAN_ORBITAL_COMMAND("Orbital Command"),
    TERRAN_ORBITAL_COMMAND_FLYING("Flying Orbital Command"),
    TERRAN_PLANETARY_FORTRESS("Planetary Fortress"),
    TERRAN_RAVEN("Raven"),
    TERRAN_REAPER("Reaper"),
    TERRAN_REFINERY("Refinery"),
    TERRAN_REFINERY_RICH("Rich Refinery"),
    TERRAN_SCV("SCV"),
    TERRAN_SENSOR_TOWER("Sensor Tower"),
    TERRAN_SIEGE_TANK("Siege Tank"),
    TERRAN_SIEGE_TANK_SIEGED("Sieged Siege Tank"),
    TERRAN_STARPORT("Starport"),
    TERRAN_STARPORT_FLYING("Flying Starport"),
    TERRAN_STARPORT_REACTOR("Starport Reactor"),
    TERRAN_STARPORT_TECHLAB("Starport Tech Lab"),
    TERRAN_SUPPLY_DEPOT("Supply Depot"),
    TERRAN_SUPPLY_DEPOT_LOWERED("Lowered Supply Depot"),
    TERRAN_THOR("Thor"),
    TERRAN_THOR_AP("Thor"),
    TERRAN_VIKING_ASSAULT("Viking Assault"),
    TERRAN_VIKING_FIGHTER("Viking Fighter"),
    TERRAN_WIDOWMINE("Widow Mine"),
    TERRAN_WIDOWMINE_BURROWED("Burrowed Widow Mine"),
    // ZERG
    ZERG_BANELING("Baneling"),
    ZERG_BANELING_BURROWED("Burrowed Baneling"),
    ZERG_BANELING_COCOON("Baneling Cocoon"),
    ZERG_BANELING_NEST("Baneling Nest"),
    ZERG_BROODLING("Broodling"),
    ZERG_BROODLORD("Broodlord"),
    ZERG_BROODLORD_COCOON("Broodlord Cocoon"),
    ZERG_CHANGELING("Changeling"),
    ZERG_CHANGELING_MARINE("Changeling Marine"),
    ZERG_CHANGELING_MARINE_SHIELD("Changeling Marine Shield"),
    ZERG_CHANGELING_ZEALOT("Changeling Zealot"),
    ZERG_CHANGELING_ZERGLING("Changeling Zergling"),
    ZERG_CHANGELING_ZERGLING_WINGS("Changeling Zergling Wings"),
    ZERG_CORRUPTOR("Corruptor"),
    ZERG_CREEP_TUMOR("Creep Tumor"),
    ZERG_CREEP_TUMOR_BURROWED("Burrowed Creep Tumor"),
    ZERG_CREEP_TUMOR_QUEEN("Creep Tumor Queen"),
    ZERG_DRONE("Drone"),
    ZERG_DRONE_BURROWED("Burrowed Drone"),
    ZERG_EGG("Egg"),
    ZERG_EVOLUTION_CHAMBER("Evolution Chamber"),
    ZERG_EXTRACTOR("Extractor"),
    ZERG_EXTRACTOR_RICH("Rich Extractor"),
    ZERG_GREATER_SPIRE("Greater Spire"),
    ZERG_HATCHERY("Hatchery"),
    ZERG_HYDRALISK("Hydralisk"),
    ZERG_HYDRALISK_BURROWED("Burrowed Hydralisk"),
    ZERG_HYDRALISK_DEN("Hydralisk Den"),
    ZERG_INFESTATION_PIT("Infestation Pit"),
    ZERG_INFESTED_TERRANS_EGG("Infested Terrans Egg"),
    ZERG_INFESTOR("Infestor"),
    ZERG_INFESTOR_BURROWED("Burrowed Infestor"),
    ZERG_INFESTOR_TERRAN("Infestor Terran"),
    ZERG_LAIR("Lair"),
    ZERG_LARVA("Larva"),
    ZERG_LOCUS_TMP("Locust"),
    ZERG_LOCUS_TMP_FLYING("Flying Locust"),
    ZERG_LURKER_DEN_MP("Lurker Den"),
    ZERG_LURKER_MP("Lurker"),
    ZERG_LURKER_MP_BURROWED("Burrowed Lurker"),
    ZERG_LURKER_MP_EGG("Lurker Egg"),
    ZERG_MUTALISK("Mutalisk"),
    ZERG_NYDUS_CANAL("Nydus Canal"),
    ZERG_NYDUS_NETWORK("Nydus Network"),
    ZERG_OVERLORD("Overlord"),
    ZERG_OVERLORD_COCOON("Overlord Cocoon"),
    ZERG_OVERLORD_TRANSPORT("Overlord Transport"),
    ZERG_OVERSEER("Overseer"),
    ZERG_QUEEN("Queen"),
    ZERG_QUEEN_BURROWED("Burrowed Queen"),
    ZERG_RAVAGER("Ravager"),
    ZERG_RAVAGER_COCOON("Ravager Cocoon"),
    ZERG_ROACH("Roach"),
    ZERG_ROACH_BURROWED("Burrowed Roach"),
    ZERG_ROACH_WARREN("Roach Warren"),
    ZERG_SPAWNING_POOL("Spawning Pool"),
    ZERG_SPINE_CRAWLER("Spine Crawler"),
    ZERG_SPINE_CRAWLER_UPROOTED("Uprooted Spine Crawler"),
    ZERG_SPIRE("Spire"),
    ZERG_SPORE_CRAWLER("Spore Crawler"),
    ZERG_SPORE_CRAWLER_UPROOTED("Uprooted Spore Crawler"),
    ZERG_SWARM_HOST_BURROWED_MP("Burrowed Swarm Host"),
    ZERG_SWARM_HOST_MP("Swarm Host"),
    ZERG_TRANSPORT_OVERLORD_COCOON("Transport Overlord Cocoon"),
    ZERG_ULTRALISK("Ultralisk"),
    ZERG_ULTRALISK_CAVERN("Ultralisk Cavern"),
    ZERG_VIPER("Viper"),
    ZERG_ZERGLING("Zergling"),
    ZERG_ZERGLING_BURROWED("Burrowed Zergling"),
    ZERG_ULTRALISK_BURROWED("Burrowed Ultralisk"),
    ZERG_RAVAGER_BURROWED("Burrowed Ravager"),
    ZERG_INFESTOR_TERRAN_BURROWED("Burrowed Infestor Terran"),
    ZERG_OVERSEER_SIEGED("Sieged Overseer"),
    //PROTOSS
    PROTOSS_ADEPT("Adept"),
    PROTOSS_ADEPT_PHASE_SHIFT("Adept (Phase Shift)"),
    PROTOSS_ARCHON("Archon"),
    PROTOSS_ASSIMILATOR("Assimilator"),
    PROTOSS_ASSIMILATOR_RICH("Rich Assimilator"),
    PROTOSS_CARRIER("Carrier"),
    PROTOSS_COLOSSUS("Colossus"),
    PROTOSS_CYBERNETICS_CORE("Cybernetics Core"),
    PROTOSS_DARK_SHRINE("Dark Shrine"),
    PROTOSS_DARK_TEMPLAR("Dark Templar"),
    PROTOSS_DISRUPTOR("Disruptor"),
    PROTOSS_DISRUPTOR_PHASED("Disruptor (Phased)"),
    PROTOSS_FLEET_BEACON("Fleet Beacon"),
    PROTOSS_FORGE("Forge"),
    PROTOSS_GATEWAY("Gateway"),
    PROTOSS_HIGH_TEMPLAR("High Templar"),
    PROTOSS_IMMORTAL("Immortal"),
    PROTOSS_INTERCEPTOR("Interceptor"),
    PROTOSS_MOTHERSHIP("Mothership"),
    PROTOSS_MOTHER_SHIP_CORE("Mothership Core"),
    PROTOSS_NEXUS("Nexus"),
    PROTOSS_OBSERVER("Observer"),
    PROTOSS_ORACLE("Oracle"),
    PROTOSS_ORACLE_STASIS_TRAP("Oracle (Stasis Trap)"),
    PROTOSS_PHOENIX("Phoenix"),
    PROTOSS_PHOTON_CANNON("Photon Cannon"),
    PROTOSS_PROBE("Probe"),
    PROTOSS_PYLON("Pylon"),
    PROTOSS_PYLON_OVERCHARGED("Overcharged Pylon"),
    PROTOSS_ROBOTICS_BAY("Robotics Bay"),
    PROTOSS_ROBOTICS_FACILITY("Robotics Facility"),
    PROTOSS_SENTRY("Sentry"),
    PROTOSS_SHIELD_BATTERY("Shield Battery"),
    PROTOSS_STALKER("Stalker"),
    PROTOSS_STARGATE("Stargate"),
    PROTOSS_TEMPEST("Tempest"),
    PROTOSS_TEMPLAR_ARCHIVE("Templar Archive"),
    PROTOSS_TWILIGHT_COUNCIL("Twilight Council"),
    PROTOSS_VOIDRAY("Void Ray"),
    PROTOSS_WARP_GATE("Warp Gate"),
    PROTOSS_WARP_PRISM("Warp Prism"),
    PROTOSS_WARP_PRISM_PHASING("Warp Prism (Phasing)"),
    PROTOSS_ZEALOT("Zealot"),
    PROTOSS_OBSERVER_SIEGED("Sieged Observer")

    ;

    private static final Map<String, String> labelMap;

    static {
        labelMap = new HashMap<>();
        for (UnitTypeNames unitType : UnitTypeNames.values()) {
            labelMap.put(unitType.name(), unitType.label);
        }
    }

    private final String label;
    UnitTypeNames(String label) {
        this.label = label;
    }

    public String getLabel() {
        return label;
    }

    public static String getLabelFromName(String name) {
        if (labelMap.containsKey(name)) {
            return labelMap.get(name);
        }
        return "unknown";
    }
}